<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Transversal\CleanShop.Transversal.Common\CleanShop.Transversal.Common.csproj" />
    <ProjectReference Include="..\CleanShop.Application.DTO\CleanShop.Application.DTO.csproj" />
  </ItemGroup>

</Project>
