<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CleanShop.Entity\CleanShop.Entity.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>CleanShop.Domain.Interface</AssemblyName>
    <RootNamespace>CleanShop.Domain.Interface</RootNamespace>
  </PropertyGroup>

</Project>
